name: Gerar APK
on:
  pull_request:
    branches:
      - master
jobs:
  # Job para gerar um APK de Debug e realizar upload para o Github
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gerar o build com o Gradle
        run: ./gradlew build

      - name: Upload do APK para o Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.7.0
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: QAs
          file: app/build/outputs/apk/debug/app-debug.apk
